---
output:
  pdf_document: default
  html_document: default
  word_document: default
---

# Code Book

This document provides the insight into how the entire process of getting the required means was carried out inside run_analysis.R.

**1.Reading files into data tables**
-After downloading the data set, I used 'read.table' command to assign variables to the various data sets.

*features <- features.txt* contains 561 obs. of 2 variables. The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals.

*activity <- activity_labels.txt* contains 6 obs. of 2 variables.The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals

*x_test <- X_test.txt* contains 2947 obs. of 561 variables. It contains recorded features test data.

*y_test <- y_test.txt* contains 2947 obs. of 1 variable. It basically contains test data of activities’code labels.

*subject_test <- subject_test.txt* contains 2947 obs. of 1 variable. It contains test data for 9 of the 30 volunteers.

*x_train <- X_train.txt* contains 7352 obs. of 561 variables. It contains recorded features train data. 

*y_train <- y_train.txt* contains 7352 obs. of 1 variable. It basically contains train data of activities’code labels.

*subject_train <- subject_train.txt* contains 7352 obs. of 1 vaariable. It contains train data for 21 of the 30 volunteers.

**2.Renaming Columns**
-Renamed the single column of 'subject_train' and 'subject_test' to "ID". Similarly, renamed 'y_test' and 'y_train' column "label".

-Also renmaed the column names of 'x_train' and 'x_test' with the formulas column of features using:

*names(x_train) <- c(as.character(features$formulas))*

*names(x_test) <- c(as.character(features$formulas))*

**3.Merging Data**
-Combined the test data using cbind creating new data table 'joined_test' having 2947 obs. and 563 variables.

-Similarly created 'joined_train' combing train data having 7352 obs. and 563 variables.

-Finally made a joint table of test and train data using rbind to have a new data table named 'comb_data' having 10299 obs. and 563 variables.

**4.Extracting only Mean and Standard deviation**
-Used grep function to identify columns with mean or std and stored the result in 'stdmeancols' having identified 86 columns.

-Since we cant to keep the ID and label columns as well, we have another variable 'req_columns' having the first 2 columns alongwtih the stdmeancols.

-Finally, we extract the required columns and save the result in a new cariable called 'extracted_data' having 10299 obs. and 88 variables.

**5.Using Descriptive Activity Names**
-All the activity labels in the 'extracted_data' is replaced with full activity names.

**6.Having Descriptive Variable Names**
-Removed regular expressions from the names to be more relevent. However, I did not rename the entire variables as it would have made it all too verbose. The current state is concise and understandable.

**7.Calculating Mean in a Separate Data Table**
-After grouping the data, calculated the mean and saved it in a separate table called 'finalized'.
Wrote the data table into a txt file as instructed.



